defaults:
  - _self_
  - model: dynedge
  - trainer: default

run:
  timestamp: ${now:%Y%m%d-%H%M%S}
  n_folds: 5
  fold: 0
  seed: 48
  logging: True
  train_file: folds_10.parquet

comp_name: icecube-neutrinos-in-deep-ice
storage_drive: storage_dimm2

hydra:
  run:
    dir: /mnt/${storage_drive}/kaggle_output/${comp_name}/${run.timestamp}/${model.model_name}/fold_${run.fold}/
# sweep:
#   dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
#   subdir: ${hydra.job.num}
