max_epochs: 8
accelerator: gpu
devices: 2
strategy: ddp
precision: 16
sync_batchnorm: True
# limit_train_batches: 0.05
# limit_val_batches: 0.05
val_check_interval: 0.5
gradient_clip_val: 0.5
log_every_n_steps: 100
